import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  weight: ["600", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}capitalize  max-w-screen-xl py-6 px-3 mx-auto antialiased`}
      >
        <Toaster className="capitalize " />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
// project
// auth => login , Register , contextToken , .env
// Forgot Password , Verify Reset Code
//
//
//
//
//
//
// * //
