import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/Layout/Navbar/Navbar";

const roboto_Mono = Roboto_Mono({
  weight: ["600", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_Mono.className}capitalize  bg-muted  antialiased`}
      >
        <Toaster className="capitalize " />
        <QueryProvider>
          <Navbar />
          <div className=" max-w-screen-xl py-6 px-3 mx-auto">{children}</div>
        </QueryProvider>
      </body>
    </html>
  );
}
// project
// auth => login , Register , contextToken , .env
// Forgot Password , Verify Reset Code
//
//
//
//
//
//
// * //
