import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/Layout/Navbar/Navbar";
import Footer from "@/Layout/Footer/Footer";
import Arrow from "@/Layout/Arrow";

const outfit = Outfit({
  weight: ["600", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} capitalize  bg-muted  antialiased`}>
        <Toaster className="capitalize " />
        <QueryProvider>
          <Navbar />
          <div className=" max-w-screen-xl pt-22  py-12 px-3 mx-auto">
            {children}
          </div>

          <Arrow />
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
